import { Roboto } from 'next/font/google'
import '@/styles/reset.scss'
import '@/styles/global.scss'
import Header from '@/components/Header'
import AuthPopup from '@/containers/AuthPopup'
const roboto = Roboto({ subsets: ['latin'], weight:['100','400','300'], })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  return (
    <html lang="en">
       
      <body className={roboto.className}>
        <AuthPopup />
        {children}
        </body>
    </html>
  )
}
